import type { ProjectConfig } from '#/config';

const setting: ProjectConfig = {
  theme: 'light',
  layoutType: 'sidebar',
  systemColor: '#165DFF',
  topColor: '#FFFFFF',
  menuColor: '#FFFFFF',
  splitMenu: true,
  fixMenu: false,
  closeMenu: false,
  collapsed: true,
  activityMenu: false,
  menuSearch: true,
  accordion: false,
  collapsedMenuName: false,
  headerFix: false,
  sidebarFix: false,
  mixMenuType: 'hover',
  topMenuType: 'center',
  showCollapsedButton: true,
  contentWitdh: 'flow',
  lockScreen: 0,
  menuWidth: 220,
  menuTheme: 'light',
  breadcrumb: true,
  breadcrumbIcon: true,
  tabBar: true,
  tabType: 'rounded',
  tabRefresh: true,
  tabFast: false,
  tabFold: false,
  bannerNotice: true,
  leftMenu: true,
  topNavbar: true,
  showLogo: true,
  showFooter: true,
  fullScreen: false,
  colorGrey: false,
  colorWeak: false,
  topProgress: false,
  loading: false,
  routerAnimation: true,
  animationType: 'scale',
  globalSettings: false,
  device: 'desktop',
  menuFromServer: false,
  serverMenu: [],
};

export default setting;
